name: _test

on:
  workflow_call:


jobs:

  TestServer:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r server/requirements.txt
          pip install pytest pytest-cov pytest-mock

      - name: Run Tests
        run: |
          find server/src/ -type d -exec touch {}/__init__.py \;
          find server/tests/ -type d -exec touch {}/__init__.py \;
          python -m pytest --cov-config=server/tests/.coveragerc --cov=server/src server/tests/ --cov-report term-missing
